stages:
  train:
    cmd: src/ml_pipeline-for-deploymen.py
    deps:
    - data/interim/raw_useful_ftrs.csv
    - data/interim/features_to_use_summary.csv
    outs:	
    - data/ui/input_data_sample.csv
    metrics:
    - "src/metrics/metrics.json":
        cache: false